# Generated by Django 5.1.3 on 2024-11-17 11:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transfer", "0002_clipboardcontent"),
    ]

    operations = [
        migrations.CreateModel(
            name="EncryptedClipboard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("encrypted_content", models.BinaryField()),
                ("encryption_key", models.BinaryField()),
                ("retrieval_code", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="EncryptedFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_name", models.CharField(max_length=255)),
                ("encrypted_data", models.BinaryField()),
                ("encryption_key", models.BinaryField()),
                ("retrieval_code", models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
