# Generated by Django 5.1.3 on 2024-11-18 02:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transfer", "0003_encryptedclipboard_encryptedfile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clipboardcontent",
            name="retrieval_code",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
